//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlogAppWcf
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BlogDbEntities : DbContext
    {
        public BlogDbEntities()
            : base("name=BlogDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Post> Post { get; set; }
        public virtual DbSet<User> User { get; set; }
    
        public virtual int DeletePost(Nullable<int> post_id)
        {
            var post_idParameter = post_id.HasValue ?
                new ObjectParameter("post_id", post_id) :
                new ObjectParameter("post_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeletePost", post_idParameter);
        }
    
        public virtual int InsertNewPost(string body, Nullable<int> user_id)
        {
            var bodyParameter = body != null ?
                new ObjectParameter("body", body) :
                new ObjectParameter("body", typeof(string));
    
            var user_idParameter = user_id.HasValue ?
                new ObjectParameter("user_id", user_id) :
                new ObjectParameter("user_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertNewPost", bodyParameter, user_idParameter);
        }
    }
}
