//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlogAppWcf
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        public int Id { get; set; }
        public string Body { get; set; }
        public System.DateTime Created_At { get; set; }
        public Nullable<System.DateTime> Modified_At { get; set; }
        public int User_Id { get; set; }
    
        public virtual User User { get; set; }
    }
}
