//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlogApp.BlogService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClientInfo", Namespace="http://schemas.datacontract.org/2004/07/BlogAppWcf")]
    [System.SerializableAttribute()]
    public partial class ClientInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GuidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int User_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string guid1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int user_Id1Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Guid {
            get {
                return this.GuidField;
            }
            set {
                if ((object.ReferenceEquals(this.GuidField, value) != true)) {
                    this.GuidField = value;
                    this.RaisePropertyChanged("Guid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int User_Id {
            get {
                return this.User_IdField;
            }
            set {
                if ((this.User_IdField.Equals(value) != true)) {
                    this.User_IdField = value;
                    this.RaisePropertyChanged("User_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="guid")]
        public string guid1 {
            get {
                return this.guid1Field;
            }
            set {
                if ((object.ReferenceEquals(this.guid1Field, value) != true)) {
                    this.guid1Field = value;
                    this.RaisePropertyChanged("guid1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="user_Id")]
        public int user_Id1 {
            get {
                return this.user_Id1Field;
            }
            set {
                if ((this.user_Id1Field.Equals(value) != true)) {
                    this.user_Id1Field = value;
                    this.RaisePropertyChanged("user_Id1");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserNotFoundFault", Namespace="http://schemas.datacontract.org/2004/07/BlogAppWcf")]
    [System.SerializableAttribute()]
    public partial class UserNotFoundFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NotCorrectPasswordFault", Namespace="http://schemas.datacontract.org/2004/07/BlogAppWcf")]
    [System.SerializableAttribute()]
    public partial class NotCorrectPasswordFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PostNotFoundFault", Namespace="http://schemas.datacontract.org/2004/07/BlogAppWcf")]
    [System.SerializableAttribute()]
    public partial class PostNotFoundFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserAlreadyExistsFault", Namespace="http://schemas.datacontract.org/2004/07/BlogAppWcf")]
    [System.SerializableAttribute()]
    public partial class UserAlreadyExistsFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PasswordsNotEqualFault", Namespace="http://schemas.datacontract.org/2004/07/BlogAppWcf")]
    [System.SerializableAttribute()]
    public partial class PasswordsNotEqualFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PostModel", Namespace="http://schemas.datacontract.org/2004/07/BlogAppWcf")]
    [System.SerializableAttribute()]
    public partial class PostModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BodyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Created_AtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> Modified_AtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BlogApp.BlogService.UserModel UserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int User_IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Body {
            get {
                return this.BodyField;
            }
            set {
                if ((object.ReferenceEquals(this.BodyField, value) != true)) {
                    this.BodyField = value;
                    this.RaisePropertyChanged("Body");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Created_At {
            get {
                return this.Created_AtField;
            }
            set {
                if ((this.Created_AtField.Equals(value) != true)) {
                    this.Created_AtField = value;
                    this.RaisePropertyChanged("Created_At");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Modified_At {
            get {
                return this.Modified_AtField;
            }
            set {
                if ((this.Modified_AtField.Equals(value) != true)) {
                    this.Modified_AtField = value;
                    this.RaisePropertyChanged("Modified_At");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BlogApp.BlogService.UserModel User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int User_Id {
            get {
                return this.User_IdField;
            }
            set {
                if ((this.User_IdField.Equals(value) != true)) {
                    this.User_IdField = value;
                    this.RaisePropertyChanged("User_Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserModel", Namespace="http://schemas.datacontract.org/2004/07/BlogAppWcf")]
    [System.SerializableAttribute()]
    public partial class UserModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Created_AtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> Last_LoginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BlogApp.BlogService.PostModel[] PostField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Created_At {
            get {
                return this.Created_AtField;
            }
            set {
                if ((this.Created_AtField.Equals(value) != true)) {
                    this.Created_AtField = value;
                    this.RaisePropertyChanged("Created_At");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Last_Login {
            get {
                return this.Last_LoginField;
            }
            set {
                if ((this.Last_LoginField.Equals(value) != true)) {
                    this.Last_LoginField = value;
                    this.RaisePropertyChanged("Last_Login");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BlogApp.BlogService.PostModel[] Post {
            get {
                return this.PostField;
            }
            set {
                if ((object.ReferenceEquals(this.PostField, value) != true)) {
                    this.PostField = value;
                    this.RaisePropertyChanged("Post");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BlogService.IBlogAppService")]
    public interface IBlogAppService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBlogAppService/UserLogin", ReplyAction="http://tempuri.org/IBlogAppService/UserLoginResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(BlogApp.BlogService.UserNotFoundFault), Action="http://tempuri.org/IBlogAppService/UserLoginUserNotFoundFaultFault", Name="UserNotFoundFault", Namespace="http://schemas.datacontract.org/2004/07/BlogAppWcf")]
        [System.ServiceModel.FaultContractAttribute(typeof(BlogApp.BlogService.NotCorrectPasswordFault), Action="http://tempuri.org/IBlogAppService/UserLoginNotCorrectPasswordFaultFault", Name="NotCorrectPasswordFault", Namespace="http://schemas.datacontract.org/2004/07/BlogAppWcf")]
        BlogApp.BlogService.ClientInfo UserLogin(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBlogAppService/UserLogin", ReplyAction="http://tempuri.org/IBlogAppService/UserLoginResponse")]
        System.Threading.Tasks.Task<BlogApp.BlogService.ClientInfo> UserLoginAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBlogAppService/UserLogout", ReplyAction="http://tempuri.org/IBlogAppService/UserLogoutResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(BlogApp.BlogService.UserNotFoundFault), Action="http://tempuri.org/IBlogAppService/UserLogoutUserNotFoundFaultFault", Name="UserNotFoundFault", Namespace="http://schemas.datacontract.org/2004/07/BlogAppWcf")]
        void UserLogout(BlogApp.BlogService.ClientInfo client);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBlogAppService/UserLogout", ReplyAction="http://tempuri.org/IBlogAppService/UserLogoutResponse")]
        System.Threading.Tasks.Task UserLogoutAsync(BlogApp.BlogService.ClientInfo client);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBlogAppService/AddPost", ReplyAction="http://tempuri.org/IBlogAppService/AddPostResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(BlogApp.BlogService.UserNotFoundFault), Action="http://tempuri.org/IBlogAppService/AddPostUserNotFoundFaultFault", Name="UserNotFoundFault", Namespace="http://schemas.datacontract.org/2004/07/BlogAppWcf")]
        void AddPost(string body, BlogApp.BlogService.ClientInfo client);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBlogAppService/AddPost", ReplyAction="http://tempuri.org/IBlogAppService/AddPostResponse")]
        System.Threading.Tasks.Task AddPostAsync(string body, BlogApp.BlogService.ClientInfo client);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBlogAppService/ModifyPost", ReplyAction="http://tempuri.org/IBlogAppService/ModifyPostResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(BlogApp.BlogService.PostNotFoundFault), Action="http://tempuri.org/IBlogAppService/ModifyPostPostNotFoundFaultFault", Name="PostNotFoundFault", Namespace="http://schemas.datacontract.org/2004/07/BlogAppWcf")]
        [System.ServiceModel.FaultContractAttribute(typeof(BlogApp.BlogService.UserNotFoundFault), Action="http://tempuri.org/IBlogAppService/ModifyPostUserNotFoundFaultFault", Name="UserNotFoundFault", Namespace="http://schemas.datacontract.org/2004/07/BlogAppWcf")]
        void ModifyPost(int id, string body, BlogApp.BlogService.ClientInfo client);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBlogAppService/ModifyPost", ReplyAction="http://tempuri.org/IBlogAppService/ModifyPostResponse")]
        System.Threading.Tasks.Task ModifyPostAsync(int id, string body, BlogApp.BlogService.ClientInfo client);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBlogAppService/DeletePost", ReplyAction="http://tempuri.org/IBlogAppService/DeletePostResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(BlogApp.BlogService.PostNotFoundFault), Action="http://tempuri.org/IBlogAppService/DeletePostPostNotFoundFaultFault", Name="PostNotFoundFault", Namespace="http://schemas.datacontract.org/2004/07/BlogAppWcf")]
        [System.ServiceModel.FaultContractAttribute(typeof(BlogApp.BlogService.UserNotFoundFault), Action="http://tempuri.org/IBlogAppService/DeletePostUserNotFoundFaultFault", Name="UserNotFoundFault", Namespace="http://schemas.datacontract.org/2004/07/BlogAppWcf")]
        void DeletePost(int id, BlogApp.BlogService.ClientInfo client);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBlogAppService/DeletePost", ReplyAction="http://tempuri.org/IBlogAppService/DeletePostResponse")]
        System.Threading.Tasks.Task DeletePostAsync(int id, BlogApp.BlogService.ClientInfo client);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBlogAppService/RegisterUser", ReplyAction="http://tempuri.org/IBlogAppService/RegisterUserResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(BlogApp.BlogService.UserAlreadyExistsFault), Action="http://tempuri.org/IBlogAppService/RegisterUserUserAlreadyExistsFaultFault", Name="UserAlreadyExistsFault", Namespace="http://schemas.datacontract.org/2004/07/BlogAppWcf")]
        [System.ServiceModel.FaultContractAttribute(typeof(BlogApp.BlogService.PasswordsNotEqualFault), Action="http://tempuri.org/IBlogAppService/RegisterUserPasswordsNotEqualFaultFault", Name="PasswordsNotEqualFault", Namespace="http://schemas.datacontract.org/2004/07/BlogAppWcf")]
        void RegisterUser(string username, string password, string RetryPassword, string FirstName, string LastName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBlogAppService/RegisterUser", ReplyAction="http://tempuri.org/IBlogAppService/RegisterUserResponse")]
        System.Threading.Tasks.Task RegisterUserAsync(string username, string password, string RetryPassword, string FirstName, string LastName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBlogAppService/GetAllPosts", ReplyAction="http://tempuri.org/IBlogAppService/GetAllPostsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(BlogApp.BlogService.UserNotFoundFault), Action="http://tempuri.org/IBlogAppService/GetAllPostsUserNotFoundFaultFault", Name="UserNotFoundFault", Namespace="http://schemas.datacontract.org/2004/07/BlogAppWcf")]
        BlogApp.BlogService.PostModel[] GetAllPosts(BlogApp.BlogService.ClientInfo client);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBlogAppService/GetAllPosts", ReplyAction="http://tempuri.org/IBlogAppService/GetAllPostsResponse")]
        System.Threading.Tasks.Task<BlogApp.BlogService.PostModel[]> GetAllPostsAsync(BlogApp.BlogService.ClientInfo client);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBlogAppService/GetUserPosts", ReplyAction="http://tempuri.org/IBlogAppService/GetUserPostsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(BlogApp.BlogService.UserNotFoundFault), Action="http://tempuri.org/IBlogAppService/GetUserPostsUserNotFoundFaultFault", Name="UserNotFoundFault", Namespace="http://schemas.datacontract.org/2004/07/BlogAppWcf")]
        BlogApp.BlogService.PostModel[] GetUserPosts(BlogApp.BlogService.ClientInfo client);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBlogAppService/GetUserPosts", ReplyAction="http://tempuri.org/IBlogAppService/GetUserPostsResponse")]
        System.Threading.Tasks.Task<BlogApp.BlogService.PostModel[]> GetUserPostsAsync(BlogApp.BlogService.ClientInfo client);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBlogAppService/GetPostBody", ReplyAction="http://tempuri.org/IBlogAppService/GetPostBodyResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(BlogApp.BlogService.PostNotFoundFault), Action="http://tempuri.org/IBlogAppService/GetPostBodyPostNotFoundFaultFault", Name="PostNotFoundFault", Namespace="http://schemas.datacontract.org/2004/07/BlogAppWcf")]
        [System.ServiceModel.FaultContractAttribute(typeof(BlogApp.BlogService.UserNotFoundFault), Action="http://tempuri.org/IBlogAppService/GetPostBodyUserNotFoundFaultFault", Name="UserNotFoundFault", Namespace="http://schemas.datacontract.org/2004/07/BlogAppWcf")]
        string GetPostBody(int id, BlogApp.BlogService.ClientInfo client);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBlogAppService/GetPostBody", ReplyAction="http://tempuri.org/IBlogAppService/GetPostBodyResponse")]
        System.Threading.Tasks.Task<string> GetPostBodyAsync(int id, BlogApp.BlogService.ClientInfo client);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBlogAppServiceChannel : BlogApp.BlogService.IBlogAppService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BlogAppServiceClient : System.ServiceModel.ClientBase<BlogApp.BlogService.IBlogAppService>, BlogApp.BlogService.IBlogAppService {
        
        public BlogAppServiceClient() {
        }
        
        public BlogAppServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BlogAppServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BlogAppServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BlogAppServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public BlogApp.BlogService.ClientInfo UserLogin(string username, string password) {
            return base.Channel.UserLogin(username, password);
        }
        
        public System.Threading.Tasks.Task<BlogApp.BlogService.ClientInfo> UserLoginAsync(string username, string password) {
            return base.Channel.UserLoginAsync(username, password);
        }
        
        public void UserLogout(BlogApp.BlogService.ClientInfo client) {
            base.Channel.UserLogout(client);
        }
        
        public System.Threading.Tasks.Task UserLogoutAsync(BlogApp.BlogService.ClientInfo client) {
            return base.Channel.UserLogoutAsync(client);
        }
        
        public void AddPost(string body, BlogApp.BlogService.ClientInfo client) {
            base.Channel.AddPost(body, client);
        }
        
        public System.Threading.Tasks.Task AddPostAsync(string body, BlogApp.BlogService.ClientInfo client) {
            return base.Channel.AddPostAsync(body, client);
        }
        
        public void ModifyPost(int id, string body, BlogApp.BlogService.ClientInfo client) {
            base.Channel.ModifyPost(id, body, client);
        }
        
        public System.Threading.Tasks.Task ModifyPostAsync(int id, string body, BlogApp.BlogService.ClientInfo client) {
            return base.Channel.ModifyPostAsync(id, body, client);
        }
        
        public void DeletePost(int id, BlogApp.BlogService.ClientInfo client) {
            base.Channel.DeletePost(id, client);
        }
        
        public System.Threading.Tasks.Task DeletePostAsync(int id, BlogApp.BlogService.ClientInfo client) {
            return base.Channel.DeletePostAsync(id, client);
        }
        
        public void RegisterUser(string username, string password, string RetryPassword, string FirstName, string LastName) {
            base.Channel.RegisterUser(username, password, RetryPassword, FirstName, LastName);
        }
        
        public System.Threading.Tasks.Task RegisterUserAsync(string username, string password, string RetryPassword, string FirstName, string LastName) {
            return base.Channel.RegisterUserAsync(username, password, RetryPassword, FirstName, LastName);
        }
        
        public BlogApp.BlogService.PostModel[] GetAllPosts(BlogApp.BlogService.ClientInfo client) {
            return base.Channel.GetAllPosts(client);
        }
        
        public System.Threading.Tasks.Task<BlogApp.BlogService.PostModel[]> GetAllPostsAsync(BlogApp.BlogService.ClientInfo client) {
            return base.Channel.GetAllPostsAsync(client);
        }
        
        public BlogApp.BlogService.PostModel[] GetUserPosts(BlogApp.BlogService.ClientInfo client) {
            return base.Channel.GetUserPosts(client);
        }
        
        public System.Threading.Tasks.Task<BlogApp.BlogService.PostModel[]> GetUserPostsAsync(BlogApp.BlogService.ClientInfo client) {
            return base.Channel.GetUserPostsAsync(client);
        }
        
        public string GetPostBody(int id, BlogApp.BlogService.ClientInfo client) {
            return base.Channel.GetPostBody(id, client);
        }
        
        public System.Threading.Tasks.Task<string> GetPostBodyAsync(int id, BlogApp.BlogService.ClientInfo client) {
            return base.Channel.GetPostBodyAsync(id, client);
        }
    }
}
